create table if not exists public.app_snapshots (
  key text primary key,
  snapshot jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.app_snapshot_history (
  id bigint generated by default as identity primary key,
  snapshot_key text not null,
  snapshot jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.app_snapshots enable row level security;
alter table public.app_snapshot_history enable row level security;

drop policy if exists "app_snapshots_read_all" on public.app_snapshots;
create policy "app_snapshots_read_all"
on public.app_snapshots
for select
to anon, authenticated
using (true);

drop policy if exists "app_snapshots_write_all" on public.app_snapshots;
create policy "app_snapshots_write_all"
on public.app_snapshots
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "app_snapshot_history_read_all" on public.app_snapshot_history;
create policy "app_snapshot_history_read_all"
on public.app_snapshot_history
for select
to anon, authenticated
using (true);

drop policy if exists "app_snapshot_history_write_all" on public.app_snapshot_history;
create policy "app_snapshot_history_write_all"
on public.app_snapshot_history
for all
to anon, authenticated
using (true)
with check (true);

insert into public.app_snapshots (key, snapshot)
values ('public', '{"version":2}'::jsonb)
on conflict (key) do nothing;

insert into public.app_snapshots (key, snapshot)
values ('draft', '{"version":2}'::jsonb)
on conflict (key) do nothing;

create index if not exists app_snapshot_history_created_at_idx
  on public.app_snapshot_history (created_at desc);